name: Build, Scan, and Push Docker Image to ACR

on:
  push:
    branches:
      - 'dev'                     
    paths:
      - 'app2/**'           
      - 'Dockerfile'             

permissions:
  id-token: write                
  contents: read                 

env:
  ACR_NAME: 'taskmanagerapp'     
  DOCKER_IMAGE_NAME: 'taskmanagerapp'  

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: >                  
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}"
            }
          auth-type: 'SERVICE_PRINCIPAL'
          enable-AzPSSession: true

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_SERVER }}   
          username: ${{ secrets.ARM_CLIENT_ID }}   
          password: ${{ secrets.ARM_CLIENT_SECRET }} 

      - name: Build Docker image for scanning
        uses: docker/build-push-action@v5
        with:
          context: .                             # Project root
          file: ./Dockerfile                     # Dockerfile location
          tags: ${{ secrets.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:v8
          load: true                             # Load locally for vulnerability scanning

      - name: Scan Docker image for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:v8
          format: 'table'                        # Table view output
          exit-code: '0'                         # Do not fail pipeline if issues found
          severity: 'CRITICAL,HIGH'              # Focus on important vulnerabilities

      - name: Push Docker image to ACR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.run_number }}
            ${{ secrets.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:v8